### ISSUE TITLE
Exception for byte arrays

### ISSUE THREAD

**Issue by deburau** [vmelamed/vm#7]
Given this class:

`        public class TestClass
        {
            public byte[] Bytes;
        }`

the following code

`            var tc = new TestClass {Bytes = new byte[8]};
            var s = tc.DumpNonRecursive();`

produces the following output:

TestClass (Xelos.Controllers.CustomerRelationshipManagementController+TestClass, Xelos, Version=3.0.14315.29336, Culture=neutral, PublicKeyToken=5dc9ad41baa435f6): 
  Bytes                    = byte[8]: 

  ATTENTION:
  The TextDumper threw an exception:
  System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
     at System.BitConverter.ToString(Byte[] value, Int32 startIndex, Int32 length)
     at lambda_method(Closure , Object , ClassDumpData , ObjectTextDumper , DumpState )
     at vm.Aspects.Diagnostics.ObjectTextDumper.DumpObject(Object obj, Type dumpMetadata, DumpAttribute dumpAttribute, DumpState parentState)
     at vm.Aspects.Diagnostics.ObjectTextDumper.Dump(Object value, Type dumpMetadata, DumpAttribute dumpAttribute)

**Comment by vmelamed** [comment]
Added a new unit test. The bug has been confirmed and fixed. Thank you!
