### ISSUE TITLE
TextDumper broken after latest NuGet-Upgrade

### ISSUE THREAD

**Issue by deburau** [vmelamed/vm#8]
After applying the latest NuGet updates, I get the following error

ATTENTION:
The TextDumper threw an exception:
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at vm.Aspects.Diagnostics.Implementation.DumpState..ctor(ObjectTextDumper dumper, Object instance, Type type, ClassDumpData classDumpData, DumpAttribute instanceDumpAttribute, DumpScript dumpScript, Boolean isTopLevelClass)
   at vm.Aspects.Diagnostics.Implementation.DumpState..ctor(ObjectTextDumper dumper, Object instance, ClassDumpData classDumpData, Boolean buildScript)
   at vm.Aspects.Diagnostics.ObjectTextDumper.DumpObject(Object obj, Type dumpMetadata, DumpAttribute dumpAttribute, DumpState parentState)
   at vm.Aspects.Diagnostics.ObjectTextDumper.Dump(Object value, Type dumpMetadata, DumpAttribute dumpAttribute)

After downgrading the CommonServiceLocator NuGet package from 2.0.1 to 1.3.0 the error was gone. Is there a better way to fix it?

**Comment by vmelamed** [comment]
Several weeks ago I tried to upgrade the CSL and Unity to their new versions but that turned to be a disaster because of the poor dependency and versioning policies of the current owners of these projects. I reverted back to 1.3. If you have the latest NuGet package it should be downloading 1.3 unless you have a dependency on 2.0.1 somewhere else in your project. Is that the case? If not, you probably upgraded to that unfortunate version of the dumper which was dependent on 2.0.1 - it downloaded it and now when you upgraded again, NuGet realized that you have a higher version and did not downgrade the CSL. So, basically by downloading 1.3 - you fixed the problem caused by this poor attempt of CSL upgrade.
In any case, I am sorry for the confusion there - it was my fault to trust the 2.0.1 "upgrade" - I should've known better when the team is no longer from Microsoft.
